language: generic
sudo: required
os:
  - linux
  - osx
osx_image: xcode9.4
branches:
  only:
    - master
    - linux-ci
env:
  global:
    - PROJECT="Schedule.xcodeproj"
    - SCHEME="Schedule-Package"
    - FRAMEWORK="Schedule"
    - IOS_SDK="iphonesimulator11.3"
    - TVOS_SDK="appletvsimulator11.3"
    - MACOS_SDK="macosx10.13"

matrix:
  include:
  - env: DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.3"    SDK="$IOS_SDK"
    os: osx
  - env: DESTINATION="arch=x86_64"    SDK="$MACOS_SDK"
    os: osx
  - env: DESTINATION="OS=11.3,name=Apple TV 4K"    SDK="$TVOS_SDK"
    os: osx
  - env: LINUX=1
    os: linux

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild clean build test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift test; fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Schedule'
  - sleep 5