language: generic
sudo: required
osx_image: xcode9.4
os:
  - linux
  - osx
branches:
  only:
    - master
    - linux-ci
env:
  global:
    - PROJECT="Schedule.xcodeproj"
    - SCHEME="Schedule-Package"
    - FRAMEWORK="Schedule"
    - IOS_SDK="iphonesimulator11.3"
    - TVOS_SDK="appletvsimulator11.3"
    - MACOS_SDK="macosx10.13"

  matrix:
    include:
    - SDK: $IOS_SDK      
      DESTINATION: platform=iOS Simulator,name=iPhone 8,OS=11.3
      os: osx

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild clean build test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift test; fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Schedule'
  - sleep 5